### ISSUE TITLE
Pauta Chapter 03/10

### ISSUE THREAD

**Issue by flaviolee** [pagarme/design#6]
## Estruturação de design

Estamos prestar a aumentar bastante o tamanho de nossa equipe de designers e até então temos pontos importantes para melhorar ou definir de uma vez por todas, visando facilitar a vida de quem entrar na hora de entender nossos processos e garantir uma vivencia saudavel com mais pessoas trabalhando paralelamente.

Para isso, acredito que precisamos definir alguns topicos, alguns bem praticos e outros mais estrategicos. Vou elencar aqui alguns deles. Por favor, acrescentem o que acharem necessario:

- [ ] Lugar correto para armazenar arquivos, sejam eles editaveis de sketch, axure ou outro software ou resultados de testes, videos de entrevistas, e demais documentos de design.

- [ ] Definir a forma como cada asset nosso deve ser armazenado, padronizando nossa forma de enxergar nossos arquivos. (Gerar relatórios depois de testes e armazenar no github? Incluir notas sobre videos de entrevistas ou testes gravados que apontem razões para uma mudança de decisão, indicando tempo do video relacionado a determinada situação?)

- [ ] Melhorar os textos de cada repositório, deixando claro seu conteudo, a diferença entre eles e se for o caso, descrevendo também como e onde os arquivos devem ser armazenados.

- [ ] Padronizar ferramentas (polemico?): DIscutir se vale a pena ou nao pensarmos nesse tipo de situação para nao haver no futuro a necessidade de termos diversos softwares diferentes para enxergar todo nosso trabalho, além de evitar que partes de um projeto estejam dividas em arquivos diferentes.

- [ ] Desenvolver templates da abordagem de design (como guias, nao como regras e levando em consideração as diferenças de contextos), visando termos um modo unificado de trabalhar em cada projeto, para tentarmos ter outputs parecidos nao importando quem esteja por trás da execução.

**Comment by flaviolee** [comment]
Ideia pra ajudar a definir esse guia de abordagens: definir alguns contextos diferentes (testes presenciais com usuario, entrevista via questionario, criação de prototipo ou desenho final de tela, etc) e a partir deles elencar os passos que achamos ideais para fazermos um bom trabalho.

Acho que assim rola ajudar a instruir, garantir o nivel do trabalho que será desenvolvido e já nos certificamos de que a devida documentação será feita.

**Comment by Fausto-Junior** [comment]
Acho que o principal é definirmos esses primeiros pontos que levantou, principalmente padronizar repositório e dar visibilidade das tarefas que estamos atacando. 

Em relação aos templates, não vejo isso com urgência, podemos utilizar os artefatos que já temos como guia e ir aperfeiçoando e subindo a régua.
